"use client";

import { theme } from "@/theme/theme";
import { ThemeProvider } from "@emotion/react";
import {
  AppBar,
  CssBaseline,
  IconButton,
  Toolbar,
  Typography,
} from "@mui/material";
import { Inter } from "next/font/google";
import { FaTwitter } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <body className={inter.className}>
          <AppBar elevation={0} position="sticky">
            <Toolbar>
              <IconButton>
                <FaTwitter color="#1da1f1" fontSize="28px" />
              </IconButton>
              <Typography>Simple Twitter</Typography>
            </Toolbar>
          </AppBar>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
